{{- range $name, $route := .Values.httpRoutes }}
{{- if and $route.backendPolicy $route.backendPolicy.enableIAP (not $route.backendPolicy.iapSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-iap
type: Opaque
data:
  client_secret: { { $route.IAP_CLIENT_SECRET | b64enc | quote } }
{{- end }}
{{- end }}